services:
  db:
    image: "postgres"
    ports:
      - 5432:5432
    env_file:
      - path: ".db.env"

  api:
    build: .
    ports:
      - "8080:80"
    env_file:
      - path: ".env"
    volumes:
      - ./:/mount/:rw
