FROM python:3.12

WORKDIR /birdsnap/
COPY ./ /birdsnap/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /birdsnap/requirements.txt 
CMD ["fastapi", "run", "main.py", "--port", "80"]